language: java
jdk:
- oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - web/src/main/web/node_modules
node_js: "8.7.0"

after_success:
  - docker build -t fundrequestio/platform:"$TRAVIS_BRANCH" rest-api
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push fundrequestio/platform:"$TRAVIS_BRANCH"